name: Deploy the nextjs app

on: 
    push:
        branches:
            - main

jobs: 
    deploy: 
        name: Push to ec2 
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Deploy to my ec2 instance 
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: 34.237.243.161
                username: ubuntu
                key: ${{ secrets.PRIVATE_SSH_KEY }}
                port: 22
                script: |
                 ls